### PR TITLE
Fix docker build

### PR DESCRIPTION
**Pull request by LivingWithHippos**
- added a working apache configuration to the image
- added a startup script that takes care of permissions
- added a docker-compose file for easier management

What is missing

- tags on dockerhub should be numbers only, right now you have V2 instead of 2. I think this breaks tha `latest` tag and the major/minor tag automatic generation
edit: tag can be anything, but you are missing the latest and major/minor tags

### CODE REVIEW

**Comment by Xtrendence** [comment]
In terms of the `latest` tag, from my understanding it's nothing actually special in terms of how Docker interprets it correct? So it's just like a best practice to set and update the most recent image with it, so I'd both have a `V.2.1.0` and a `latest` which are the same, and in the future I'd tag another image as `latest` if it's more recent?

And thank you for the help with the other Docker stuff and docker-compose support, considering your code does consider the `data` directory as a volume, it fixes issue #47? 

Lastly, I'll have to add contribution guidelines in a bit, and I'm sure you read my various comments on Reddit or here, but I'll accept any and all help with Docker-related stuff so thank you very much for your contribution, it's much appreciated, but for the main application or any bugs, I'd rather you open an issue, and if possible, steps to reproduce a bug. Obviously not applicable in this case, but just thought I'd mention it while I write the contribution document in the mean time.

**Comment by LivingWithHippos** [comment]
> In terms of the latest tag, from my understanding it's nothing actually special in terms of how Docker interprets it correct? So it's just like a best practice to set and update the most recent image with it, so I'd both have a V.2.1.0 and a latest which are the same, and in the future I'd tag another image as latest if it's more recent?

Yes, but it should be automatic. I don't know how you build your images, I've seen you have Github pro so you could set up github actions to automatically build and publish images on dockerhub every time you make a release

> And thank you for the help with the other Docker stuff and docker-compose support, considering your code does consider the data directory as a volume, it fixes issue #47?

yes 

> Lastly, I'll have to add contribution guidelines in a bit, and I'm sure you read my various comments on Reddit or here, but I'll accept any and all help with Docker-related stuff so thank you very much for your contribution, it's much appreciated, but for the main application or any bugs, I'd rather you open an issue, and if possible, steps to reproduce a bug. Obviously not applicable in this case, but just thought I'd mention it while I write the contribution document in the mean time.

thanks, I could add an issue for this one too if you want (something like ` Docker build not working`)

**Comment by Xtrendence** [comment]
No that's okay, for Docker stuff you can feel free to fix stuff without opening an issue, and I'll go over the pull request and merge it if the code's safe and whatnot. My main focus is on the application itself, so I honestly don't mind people helping with the distribution and compatibility aspects that don't touch the main code, especially because I don't have that much experience in actually distributing software, so you guys are providing a much appreciated learning opportunity in that sense, as my experience just about starts and ends with making the product.

**Comment by Xtrendence** [comment]
If you don't mind, I had another question about docker-compose. So normally, I use the `docker build` command to build the image using the Dockerfile, I then run the container, get its ID, commit it, tag the resulting image, and push to DockerHub. So now that the YAML file is there, would I simply just use `docker-compose up` to both build and run all in one command, and then do the same steps as before?

**Comment by LivingWithHippos** [comment]
The docker compose is mainly to run the container, not to build it. Of course it will build it "on the fly" if there is no image with the correct name, it doesn't give a tag so I wouldn't use it to build images. If you first use `docker build` and then `docker-compose up -d` and it would not get build a second time (you can force it to build again with `docker-compose up -d`). 

If you want to speed up you docker building process as I said you can setup Github actions. [Here](https://github.com/LivingWithHippos/unchained-bot-kotlin/blob/main/.github/workflows/docker-image.yml) I use them to build a telegram bot image on new releases and push it on dockerhub, it's pretty easy. I push only the latest tag but it should be doable to also get other tags. [Official docs](https://docs.github.com/en/actions/guides/publishing-docker-images)

**Comment by Xtrendence** [comment]
Thank you very much. I've only used GitHub actions for some Java CI, I had no idea it supported stuff like encrypted secrets for automatically deploying or pushing stuff. I'll look into this for the next release and see what it's like.

**Comment by Xtrendence** [comment]
Thank you so much for all your help. I've gotten used to using volumes now, added the `latest` tag, and there are images for `linux/amd64`, `linux/arm/v5`, `linux/arm/v7`, and `linux/arm64` now.

**Pull request merged**
